{
 "title": "Octoprint Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature Hot end",
   "type": "timeseries",
   "description": "Temperature Bed and Hotend",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "octoprint_temperatures_actual" }
   ]
  },
  {
   "title": "Percent Complete",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_progress" }
   ]
  },
  {
   "title": "Camera Stream",
   "type": "text",
   "gridPos": { "h": 11, "w": 6, "x": 16, "y": 0 },
   "options": {
    "content": "<img id=\"webcam_image\" data-bind=\"css: { flipH: settings.webcam_flipH(), flipV: settings.webcam_flipV() }, event: { load: onWebcamLoaded, error: onWebcamErrored }, visible: !webcamError()\" src=\"http://192.168.1.106/webcam/?action=stream\">"
   }
  },
  {
   "title": "Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_fan_speed" }
   ]
  },
  {
   "title": "Bed Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_temperatures_actual\n"
    }
   ]
  },
  {
   "title": "Hot End Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_temperatures_actual" }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_done_prints_total" }
   ]
  },
  {
   "title": "Failed Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_failed_prints_total" }
   ]
  },
  {
   "title": "Time Eelapsed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_time_elapsed" }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_print_time_left_estimate"
    }
   ]
  },
  {
   "title": "Extrusion this print",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "octoprint_extrusion_print" }
   ]
  },
  {
   "title": "Extrusion Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    { "expr": "octoprint_extrusion_total" }
   ]
  },
  {
   "title": " Print Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    { "expr": "octoprint_print_time_elapsed" }
   ]
  },
  { "title": "Octoprint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } }
 ]
}